#!/usr/bin/env python

import sys
import Evernote.writer as Output
import Tomboy.reader as Import

def main():
    collection = Output.Collection(sys.stdout)
    for filename in sys.argv[1:]:
        print >>sys.stderr, 'Importing {0}\n'.format(filename)
        incoming = Import.Note(filename)

        print >>sys.stderr, '>> Title: {0}\n'.format(incoming.title)
        collection.addNote(Output.Note(
            title = incoming.title,
            lastchange = incoming.lastchange,
            created = incoming.created,
            content = incoming.body_html
        ))


    print >> sys.stderr, 'Saving...'
    collection.save()


if __name__ == '__main__':
    main()


